backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/ports.md"
        label: "Ports Page"
        name: "ports"
        fields: # The fields each document in this collection have
          - {label: type, name: type, widget: hidden, default: internal}
          - {label: page, name: page, widget: hidden, default: "/ports.html"}
          - {label: title, name: title, widget: string}
          - {label: subtitle, name: subtitle, widget: string}
          - {label: Publish Date, name: date, widget: datetime, format: "YYYY-MM-DD hh:mma"}
          - {label: Image, name: image, widget: image, required: true}
          - {label: Body, name: body, widget: markdown}
      - file: "site/content/hotels.md"
        label: "Hotels Page"
        name: "hotels"
        fields: # The fields each document in this collection have
          - {label: type, name: type, widget: hidden, default: internal}
          - {label: page, name: page, widget: hidden, default: "/hotels.html"}
          - {label: title, name: title, widget: string}
          - {label: subtitle, name: subtitle, widget: string}
          - {label: Publish Date, name: date, widget: datetime, format: "YYYY-MM-DD hh:mma" }
          - {label: Image, name: image, widget: image, required: true}
          - {label: Body, name: body, widget: markdown}
      - file: "site/content/airports.md"
        label: "Airports Page"
        name: "airports"
        fields: # The fields each document in this collection have
          - {label: type, name: type, widget: hidden, default: internal}
          - {label: page, name: page, widget: hidden, default: "/airports.html"}
          - {label: title, name: title, widget: string}
          - {label: subtitle, name: subtitle, widget: string}
          - {label: Publish Date, name: date, widget: datetime, format: "YYYY-MM-DD hh:mma"}
          - {label: Image, name: image, widget: image, required: true}
          - {label: Body, name: body, widget: markdown}
      - file: "site/content/home.md"
        label: "Homepage"
        name: "home"
        fields:
          - {label: type, name: type, widget: hidden, default: home}
          - {label: url, name: url, widget: hidden, default: "index.html"}
          - {label: Title, name: title, widget: string}
          - {label: HeadingText, name: heading, widget: string}
          - {label: Image, name: image, widget: image, required: true}
          - {label: HeaderButton, name: headerButton, widget: object, fields: [
           {label: Text, name: text, widget: string},
           {label: Url, name: url, widget: string}
          ]}
          - {label: SubHeader, name: subHeading, widget: string}
          - {label: Big Message, name: bigHeaderMessage, widget: string}
          - {label: HeroBanner, name: heroBanner, widget: object, fields: [
           {label: Title, name: title, widget: string},
           {label: First paragraph(no hidde), name: first, widget: text},
           {label: Content, name: paragraph, widget: text},
           {label: SignatureName, name: signatureName, widget: string},
           {label: SignaturePosition, name: signaturePosition, widget: string}
          ]}

